### ISSUE TITLE
how can i choose  H.265 (HEVC) in code

### ISSUE THREAD

**Issue by csldali** [zteffi/OpenCV-GpuMat-NVIDIA-VIDEO-SDK-Encoder-Sample#1]
Thank you very much for your work, but I want to test h.265 (hevc) in the code. Can you point out the corresponding code for me

**Comment by zteffi** [comment]
you can use command line argument `$ ./AppEncOpenCV -codec 1`.  The project is simply slightly altered [AppEncCuda ](https://github.com/NVIDIA/video-sdk-samples/tree/master/Samples/AppEncode/AppEncCuda) sample.
