### ISSUE TITLE
Can't play the output mp4 with VLC.

### ISSUE THREAD

**Issue by yasoo7964** [zteffi/OpenCV-GpuMat-NVIDIA-VIDEO-SDK-Encoder-Sample#3]
Hi, Thanks for your this page and Ive thankfully tried it but my created output mp4 is not able to played with VLC.
Any suggestion please.
Best regards.

-------------------------------------------------
My environment is as below.
-------------------------------------------------
Windows10,
VisualStudio2019
Opencv4.5.5
NVIDIA VIdeo Codec SDK 11.1.5
cuda 11.7.1_516_94
NVIDIA GeForce Driver 516.59

-------------------------------------------------
Console messages was as below.
-------------------------------------------------
C:\TMP\recProc\x64\Release>AppEncOpenCV.exe -i sample.jpg -o video.mp4
GPU in use: NVIDIA GeForce GTX 745
[INFO ][11:42:48] Encoding Parameters:
        codec        : h264
        preset       : p3
        tuningInfo   : hq
        profile      : (default)
        chroma       : yuv420
        bitdepth     : 8
        rc           : vbr
        fps          : 30/1
        gop          : 250
        bf           : 1
        multipass    : 0
        size         : 1920x1080
        bitrate      : 0
        maxbitrate   : 0
        vbvbufsize   : 0
        vbvinit      : 0
        aq           : disabled
        temporalaq   : disabled
        lookahead    : disabled
        cq           : 0
        qmin         : P,B,I=0,0,0
        qmax         : P,B,I=0,0,0
        initqp       : P,B,I=0,0,0
Total frames encoded: 375
Bitstream saved in file video.mp4

-------------------------------------------------
and the output mp4 file is displayed by explorer as below.
-------------------------------------------------
video.mp4  2022/10/27 11:42 MP4 Video File (VLC) 1,422KB

**Comment by zteffi** [comment]
README was wrong, the sample doesn't produce .mp4  file, but a raw h.264 data by default. [FFmpeg](https://ffmpeg.org/) can be used to insert these data into any playable container, such as .mp4. Alternatively, you can use the libffmpeg to insert it into the container in your application,  but it's much more work to get the C API to work.
